[project]
name = "pitch-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amfm-decompy>=1.0.12.2",
    "librosa>=1.0.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "penn>=1.0.0",
    "praat-parselmouth>=0.4.7",
    "pysptk>=1.0.1",
    "pyworld>=0.3.5",
    "swift-f0>=0.1.2",
    "tabulate>=0.10.0",
    "torch>=2.14.0",
    "torchaudio>=2.11.0",
    "torchcrepe>=0.0.24",
    "torchfcpe>=0.0.4",
    "tqdm>=4.70.0",
]
